image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

install:
  - java -jar ./artifacts/app-card-delivery.jar &
  - java -jar ./artifacts/app-ibank.jar &

build_script:
  - ./gradlew test -Dselenide.headless=true --info
  - ./gradlew test --info
  - chmod +x gradlew